fix: build crash
src/parser/utils.ts:51:35 - error TS2339: Property 'identifier' does not exist on type 'KeywordNode | IdentifierNode | StructNode'.
  Property 'identifier' does not exist on type 'KeywordNode'.

51         node.identifier.specifier.identifier = mangle(
                                     ~~~~~~~~~~

src/parser/utils.ts:52:37 - error TS2339: Property 'identifier' does not exist on type 'KeywordNode | IdentifierNode | StructNode'.
  Property 'identifier' does not exist on type 'KeywordNode'.

52           node.identifier.specifier.identifier,
                                       ~~~~~~~~~~

src/parser/utils.ts:76:9 - error TS2367: This comparison appears to be unintentional because the types '"type_specifier"' and '"postfix"' have no overlap.

76         node.identifier.type === 'postfix'
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/parser/utils.ts:78:25 - error TS2339: Property 'expression' does not exist on type 'TypeSpecifierNode'.

78         node.identifier.expression.identifier.specifier.identifier = mangle(
                           ~~~~~~~~~~

src/parser/utils.ts:79:27 - error TS2339: Property 'expression' does not exist on type 'TypeSpecifierNode'.

79           node.identifier.expression.identifier.specifier.identifier,
                             ~~~~~~~~~~

src/parser/utils.ts:86:35 - error TS2339: Property 'identifier' does not exist on type 'KeywordNode | IdentifierNode | StructNode'.
  Property 'identifier' does not exist on type 'KeywordNode'.

86         node.identifier.specifier.identifier = mangle(
                                     ~~~~~~~~~~

src/parser/utils.ts:87:37 - error TS2339: Property 'identifier' does not exist on type 'KeywordNode | IdentifierNode | StructNode'.
  Property 'identifier' does not exist on type 'KeywordNode'.

87           node.identifier.specifier.identifier,